BASEAPI = "https://www.optionsprofitcalculator.com/ajax/getOptions"
API = "https://www.optionsprofitcalculator.com/"
SUPABASE_URL = "https://oodeitselozjqnvstmdh.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vZGVpdHNlbG96anFudnN0bWRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2MjcwODgsImV4cCI6MjA1NjIwMzA4OH0.7RrAVKjp5Idd0r_S8h7cVduEZF6J48kL5xc_f0KBhdA"
ADMIN_PASSWORD = "efiport-ib69"